print('-' * 35)
print('Tugas 1 SISOP Kelas-A')
print('-' * 35)
print('Nama: Reza Sadiya Purwadwika')
print('NPM: 21083010026')
print('-' * 35)
print('notes: ')
print('-' * 35)
print('Halo Dunia!')
print('Ini adalah skrip Bash pertamaku di Linux') 
